"""Alert routes — POST /api/tts.

Accepts a text message and returns MP3 audio bytes generated by the
TTS engine (edge-tts primary, gTTS fallback).
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from backend.src.alerts.tts_engine import TTSEngine
from backend.src.api.schemas.models import TTSRequest

logger = logging.getLogger(__name__)

router = APIRouter(tags=["alerts"])

# Singleton TTS engine
_tts_engine: TTSEngine | None = None


def get_tts_engine() -> TTSEngine:
    """Get or create the singleton TTSEngine instance.

    Returns:
        The shared TTSEngine instance.
    """
    global _tts_engine
    if _tts_engine is None:
        _tts_engine = TTSEngine()
    return _tts_engine


@router.post("/tts")
async def generate_tts(request: TTSRequest) -> Response:
    """Convert text to speech and return MP3 audio.

    Args:
        request: TTSRequest with the message text.

    Returns:
        Response with MP3 audio bytes (content-type: audio/mpeg).
        Returns 503 if all TTS backends fail.
    """
    engine = get_tts_engine()
    audio = await engine.generate_audio(request.message)

    if audio is None:
        raise HTTPException(
            status_code=503,
            detail="TTS generation failed — all backends unavailable. "
            "Alert text was logged.",
        )

    return Response(content=audio, media_type="audio/mpeg")
